In [4]:
from xml.parsers import expat

def branch_text_positions(xml_string):
    
    parser = expat.ParserCreate()

    results = []
    stack = []

    text_pos = 0  # position in tag-stripped text

    def to_branch( name ):
        tag_names = [ item['tag'] for item in stack ]
        tag_names.append( name )
        return '.'.join( tag_names )

    def start(name, attrs):
        nonlocal text_pos
        stack.append({
            "tag": name,
            "start": text_pos
        })

    def end(name):
        nonlocal text_pos
        item = stack.pop()
        item['tag'] = to_branch( item['tag'] )
        item['end'] = text_pos
        results.append(item)

    def char_data(data):
        nonlocal text_pos
        text_pos += len(data)

    parser.StartElementHandler = start
    parser.EndElementHandler = end
    parser.CharacterDataHandler = char_data

    parser.Parse(xml_string)

    return results

In [ ]:
test_tei = '''
<tei>
	<text>
		<l>some<note><text><l>a note</l></text></note>text</l>
		<l>some<note><text><l>a note</l></text></note>text</l>
		<l>some<div><text>a div</text></div>text</l>
    </text>
	<text>
		<l>some<note><text><l>a note</l></text></note>text</l>
    </text>
</tei>
'''

list( reversed( branch_text_positions( test_tei ) ) )

[{'tag': 'tei', 'start': 0, 'end': 82},
 {'tag': 'tei.text', 'start': 59, 'end': 81},
 {'tag': 'tei.text.l', 'start': 62, 'end': 76},
 {'tag': 'tei.text.l.note', 'start': 66, 'end': 72},
 {'tag': 'tei.text.l.note.text', 'start': 66, 'end': 72},
 {'tag': 'tei.text.l.note.text.l', 'start': 66, 'end': 72},
 {'tag': 'tei.text', 'start': 2, 'end': 57},
 {'tag': 'tei.text.l', 'start': 39, 'end': 52},
 {'tag': 'tei.text.l.div', 'start': 43, 'end': 48},
 {'tag': 'tei.text.l.div.text', 'start': 43, 'end': 48},
 {'tag': 'tei.text.l', 'start': 22, 'end': 36},
 {'tag': 'tei.text.l.note', 'start': 26, 'end': 32},
 {'tag': 'tei.text.l.note.text', 'start': 26, 'end': 32},
 {'tag': 'tei.text.l.note.text.l', 'start': 26, 'end': 32},
 {'tag': 'tei.text.l', 'start': 5, 'end': 19},
 {'tag': 'tei.text.l.note', 'start': 9, 'end': 15},
 {'tag': 'tei.text.l.note.text', 'start': 9, 'end': 15},
 {'tag': 'tei.text.l.note.text.l', 'start': 9, 'end': 15}]

In [30]:
for xml_path in [ item['tag'] for item in list( reversed( branch_text_positions( test_tei ) ) ) ]:
    print( xml_path )

tei
tei.text
tei.text.l
tei.text.l.note
tei.text.l.note.text
tei.text.l.note.text.l
tei.text
tei.text.l
tei.text.l.div
tei.text.l.div.text
tei.text.l
tei.text.l.note
tei.text.l.note.text
tei.text.l.note.text.l
tei.text.l
tei.text.l.note
tei.text.l.note.text
tei.text.l.note.text.l

In [2]:
from glob import glob
import pandas
from random import randrange

bp_dfs = {}

file_paths = glob( './data/edition_level/*.xml' )

print( len( file_paths ) )

15

In [5]:
file_count = 0

for file_path in file_paths:
    with open( file_path, 'r' ) as xml_file:
        try:
            xml = xml_file.read()
        except Exception as e:
            print( '')
            print( str( e ), file_path )
            with open( file_path, 'r', encoding='latin-1' ) as xml_file:
                xml = xml_file.read()
        bp = branch_text_positions( xml )
        bp_df = pandas.DataFrame( bp )
        bp_dfs[ file_path ] = bp_df
    file_count += 1
    print( file_count, end='' )
    if file_count % 30 == 0:
        print( ' ' )
    else:
        print( ', ', end='' )
        
# Quick check…
result_from_one_file = list( bp_dfs.keys() )[ randrange( len( file_paths ) ) ]
print( '\n\n', result_from_one_file, '=>' )
bp_dfs[ result_from_one_file ]

1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15,

 ./data/edition_level/Digital-marco-polo.xml =>

                                                  tag   start     end
0              TEI.teiHeader.fileDesc.titleStmt.title      39      46
1      TEI.teiHeader.fileDesc.titleStmt.respStmt.resp      84      93
2      TEI.teiHeader.fileDesc.titleStmt.respStmt.name     114     128
3           TEI.teiHeader.fileDesc.titleStmt.respStmt      63     145
4                    TEI.teiHeader.fileDesc.titleStmt      22     158
...                                               ...     ...     ...
11172                          TEI.text.body.div.list  405088  409036
11173                               TEI.text.body.div  374497  409048
11174                                   TEI.text.body  374487  409055
11175                                        TEI.text  374480  409059
11176                                             TEI       0  409060

[11177 rows x 3 columns]

In [7]:
from sklearn.feature_extraction.text import TfidfVectorizer
import pandas

doc_vectorizer = TfidfVectorizer(
    token_pattern = None,
    tokenizer = lambda s: s.split( ' ' ),  # split on space
    lowercase = False                      # keep as-is
)

branch_docs = []

for key in bp_dfs.keys():
    bp_df = bp_dfs[key]
    print( f'{len( bp_df['tag'].unique() )} unique branches in {key}' )
    branch_doc = ' '.join( bp_df['tag'].values )
    branch_docs.append( branch_doc )

tfidf_docs = doc_vectorizer.fit_transform( branch_docs )

104 unique branches in ./data/edition_level/Digital-marco-polo.xml
265 unique branches in ./data/edition_level/Chartes-de-labbaye-de-Saint-Denis.xml
186 unique branches in ./data/edition_level/Petrarchive.xml
92 unique branches in ./data/edition_level/leopardi(_).xml
541 unique branches in ./data/edition_level/beckettarchive.xml
47 unique branches in ./data/edition_level/Chronik-Ulrich-Richental.xml
230 unique branches in ./data/edition_level/Der arme Heinrich.xml
120 unique branches in ./data/edition_level/Lyrik-des-deutschen-Mittelalters.xml
93 unique branches in ./data/edition_level/4earlyChanTextsFromDunhuang_aTEIbasedEdition2017.xml
14 unique branches in ./data/edition_level/CURSUS-OnlineResourceOfMedievalLiturgicalTexts.xml
92 unique branches in ./data/edition_level/Van-gogh.xml
791 unique branches in ./data/edition_level/CoReMa.xml
121 unique branches in ./data/edition_level/Faust.xml
155 unique branches in ./data/edition_level/Kaiserchronik.xml
258 unique branches in ./data/edition_level/saba.xml

In [8]:
branch_doc

'TEI.teiHeader.fileDesc.titleStmt.title TEI.teiHeader.fileDesc.titleStmt.title TEI.teiHeader.fileDesc.titleStmt.author TEI.teiHeader.fileDesc.titleStmt.respStmt.resp TEI.teiHeader.fileDesc.titleStmt.respStmt.name TEI.teiHeader.fileDesc.titleStmt.respStmt.name TEI.teiHeader.fileDesc.titleStmt.respStmt TEI.teiHeader.fileDesc.titleStmt.respStmt.resp TEI.teiHeader.fileDesc.titleStmt.respStmt.name TEI.teiHeader.fileDesc.titleStmt.respStmt TEI.teiHeader.fileDesc.titleStmt TEI.teiHeader.fileDesc.editionStmt.edition.interpGrp.interp TEI.teiHeader.fileDesc.editionStmt.edition.interpGrp TEI.teiHeader.fileDesc.editionStmt.edition TEI.teiHeader.fileDesc.editionStmt TEI.teiHeader.fileDesc.publicationStmt.authority TEI.teiHeader.fileDesc.publicationStmt TEI.teiHeader.fileDesc.sourceDesc.listWit.witness.msDesc.msIdentifier.settlement TEI.teiHeader.fileDesc.sourceDesc.listWit.witness.msDesc.msIdentifier.repository TEI.teiHeader.fileDesc.sourceDesc.listWit.witness.msDesc.msIdentifier.idno TEI.teiHeader.fileDesc.sourceDesc.listWit.witness.msDesc.msIdentifier TEI.teiHeader.fileDesc.sourceDesc.listWit.witness.msDesc TEI.teiHeader.fileDesc.sourceDesc.listWit.witness TEI.teiHeader.fileDesc.sourceDesc.listWit.witness.emph TEI.teiHeader.fileDesc.sourceDesc.listWit.witness TEI.teiHeader.fileDesc.sourceDesc.listWit TEI.teiHeader.fileDesc.sourceDesc TEI.teiHeader.fileDesc TEI.teiHeader.profileDesc.creation.listChange.change TEI.teiHeader.profileDesc.creation.listChange.change TEI.teiHeader.profileDesc.creation.listChange.change TEI.teiHeader.profileDesc.creation.listChange.change TEI.teiHeader.profileDesc.creation.listChange.change TEI.teiHeader.profileDesc.creation.listChange.change TEI.teiHeader.profileDesc.creation.listChange TEI.teiHeader.profileDesc.creation.listChange.change TEI.teiHeader.profileDesc.creation.listChange TEI.teiHeader.profileDesc.creation TEI.teiHeader.profileDesc.creation.listChange.change TEI.teiHeader.profileDesc.creation.listChange.change TEI.teiHeader.profileDesc.creation.listChange.change TEI.teiHeader.profileDesc.creation.listChange TEI.teiHeader.profileDesc.creation TEI.teiHeader.profileDesc TEI.teiHeader.encodingDesc.variantEncoding TEI.teiHeader.encodingDesc TEI.teiHeader TEI.text.front.pb TEI.text.front.ab.lb TEI.text.front.ab.lb TEI.text.front.ab TEI.text.front.pb TEI.text.front.pb TEI.text.front.fw TEI.text.front.titlePage.lb TEI.text.front.titlePage.lb TEI.text.front.titlePage.docAuthor TEI.text.front.titlePage.lb TEI.text.front.titlePage.lb TEI.text.front.titlePage.lb TEI.text.front.titlePage.lb TEI.text.front.titlePage.lb TEI.text.front.titlePage.lb TEI.text.front.titlePage.docTitle.titlePart TEI.text.front.titlePage.docTitle TEI.text.front.titlePage.docDate TEI.text.front.titlePage.lb TEI.text.front.titlePage.lb TEI.text.front.titlePage TEI.text.front TEI.text.body.div.pb TEI.text.body.div.fw TEI.text.body.div TEI.text.body.div.div.pb TEI.text.body.div.div.fw TEI.text.body.div.div.head TEI.text.body.div.div.metamark TEI.text.body.div.div.p.lb TEI.text.body.div.div.p.lb TEI.text.body.div.div.p.mod.del.lb TEI.text.body.div.div.p.mod.del TEI.text.body.div.div.p.mod TEI.text.body.div.div.p.app.lem.mod.del TEI.text.body.div.div.p.app.lem.mod TEI.text.body.div.div.p.app.lem TEI.text.body.div.div.p.app.rdg.mod.add TEI.text.body.div.div.p.app.rdg.mod.add TEI.text.body.div.div.p.app.rdg.mod TEI.text.body.div.div.p.app.rdg TEI.text.body.div.div.p.app TEI.text.body.div.div.p.lb TEI.text.body.div.div.p.lb TEI.text.body.div.div.p.lb TEI.text.body.div.div.p.lb TEI.text.body.div.div.p.lb TEI.text.body.div.div.p.lb TEI.text.body.div.div.p.lb TEI.text.body.div.div.p.app.lem.mod.del TEI.text.body.div.div.p.app.lem.mod.add TEI.text.body.div.div.p.app.lem.mod TEI.text.body.div.div.p.app.lem TEI.text.body.div.div.p.app.rdg.mod.add TEI.text.body.div.div.p.app.rdg.mod TEI.text.body.div.div.p.app.rdg TEI.text.body.div.div.p.app TEI.text.body.div.div.p.lb TEI.text.body.div.div.p.lb TEI.text.body.div.div.p.lb TEI.text.body.div.div.p.mod.subst.del TEI.text.body.div.div.p.mod.subst.add TEI.text.body.div.div.p.mod.subst TEI.text.body.div.div.p.mod TEI.text.body.div.div.p.lb TEI.text.body.div.div.p.lb TEI.text.body.div.div.p.mod.del TEI.text.body.div.div.p.mod TEI.text.body.div.div.p.lb TEI.text.body.div.div.p.lb TEI.text.body.div.div.p TEI.text.body.div.div.p.lb TEI.text.body.div.div.p.lb TEI.text.body.div.div.p.lb TEI.text.body.div.div.p.lb TEI.text.body.div.div.p.lb TEI.text.body.div.div.p.lb TEI.text.body.div.div.p.lb TEI.text.body.div.div.p.mod.subst.add TEI.text.body.div.div.p.mod.subst.del TEI.text.body.div.div.p.mod.subst TEI.text.body.div.div.p.mod TEI.text.body.div.div.p.lb TEI.text.body.div.div.p.hi TEI.text.body.div.div.p.lb TEI.text.body.div.div.p.mod.del TEI.text.body.div.div.p.mod TEI.text.body.div.div.p.lb TEI.text.body.div.div.p.mod.subst.add TEI.text.body.div.div.p.mod.subst.del.add TEI.text.body.div.div.p.mod.subst.del.del TEI.text.body.div.div.p.mod.subst.del TEI.text.body.div.div.p.mod.subst TEI.text.body.div.div.p.mod TEI.text.body.div.div.p.lb TEI.text.body.div.div.p.lb TEI.text.body.div.div.p.lb TEI.text.body.div.div.p TEI.text.body.div.div TEI.text.body.div.div.p.pb TEI.text.body.div.div.p.fw TEI.text.body.div.div.p.lb TEI.text.body.div.div.p.subst.del.gap TEI.text.body.div.div.p.subst.del TEI.text.body.div.div.p.subst.add TEI.text.body.div.div.p.subst TEI.text.body.div.div.p.lb TEI.text.body.div.div.p.lb TEI.text.body.div.div.p.mod.subst.del.lb TEI.text.body.div.div.p.mod.subst.del TEI.text.body.div.div.p.mod.subst.add.del.lb TEI.text.body.div.div.p.mod.subst.add.del TEI.text.body.div.div.p.mod.subst.add TEI.text.body.div.div.p.mod.subst TEI.text.body.div.div.p.mod TEI.text.body.div.div.p.mod.del TEI.text.body.div.div.p.mod TEI.text.body.div.div.p.lb TEI.text.body.div.div.p.mod.del TEI.text.body.div.div.p.mod TEI.text.body.div.div.p.lb TEI.text.body.div.div.p.mod.metamark TEI.text.body.div.div.p.mod.add TEI.text.body.div.div.p.mod TEI.text.body.div.div.p.lb TEI.text.body.div.div.p.mod.subst.add TEI.text.body.div.div.p.mod.subst.del TEI.text.body.div.div.p.mod.subst TEI.text.body.div.div.p.mod TEI.text.body.div.div.p.lb TEI.text.body.div.div.p.mod.subst.add TEI.text.body.div.div.p.mod.subst.del TEI.text.body.div.div.p.mod.subst TEI.text.body.div.div.p.mod TEI.text.body.div.div.p.lb TEI.text.body.div.div.p.persName.forename TEI.text.body.div.div.p.persName TEI.text.body.div.div.p.mod.subst.add TEI.text.body.div.div.p.mod.subst.del TEI.text.body.div.div.p.mod.subst TEI.text.body.div.div.p.mod.add TEI.text.body.div.div.p.mod.del TEI.text.body.div.div.p.mod TEI.text.body.div.div.p.lb TEI.text.body.div.div.p.mod.subst.add TEI.text.body.div.div.p.mod.subst.del TEI.text.body.div.div.p.mod.subst TEI.text.body.div.div.p.mod TEI.text.body.div.div.p.lb TEI.text.body.div.div.p.lb TEI.text.body.div.div.p.lb TEI.text.body.div.div.p.mod.subst.add TEI.text.body.div.div.p.mod.subst.del TEI.text.body.div.div.p.mod.subst TEI.text.body.div.div.p.mod TEI.text.body.div.div.p.mod.del TEI.text.body.div.div.p.mod TEI.text.body.div.div.p.lb TEI.text.body.div.div.p.lb TEI.text.body.div.div.p.mod.subst.add TEI.text.body.div.div.p.mod.subst.del TEI.text.body.div.div.p.mod.subst TEI.text.body.div.div.p.mod TEI.text.body.div.div.p.choice.sic.del TEI.text.body.div.div.p.choice.sic TEI.text.body.div.div.p.choice.corr.add TEI.text.body.div.div.p.choice.corr TEI.text.body.div.div.p.choice TEI.text.body.div.div.p.lb TEI.text.body.div.div.p.lb TEI.text.body.div.div.p.lb TEI.text.body.div.div.p.lb TEI.text.body.div.div.p.lb TEI.text.body.div.div.p.app.lem.mod.subst.del TEI.text.body.div.div.p.app.lem.mod.subst.add TEI.text.body.div.div.p.app.lem.mod.subst TEI.text.body.div.div.p.app.lem.mod TEI.text.body.div.div.p.app.lem TEI.text.body.div.div.p.app.rdg.mod.subst.del TEI.text.body.div.div.p.app.rdg.mod.subst.add TEI.text.body.div.div.p.app.rdg.mod.subst TEI.text.body.div.div.p.app.rdg.mod TEI.text.body.div.div.p.app.rdg TEI.text.body.div.div.p.app TEI.text.body.div.div.p.lb TEI.text.body.div.div.p.add TEI.text.body.div.div.p.lb TEI.text.body.div.div.p.quote.lb TEI.text.body.div.div.p.quote TEI.text.body.div.div.p.lb TEI.text.body.div.div.p.lb TEI.text.body.div.div.p TEI.text.body.div.div.closer.dateline.placeName TEI.text.body.div.div.closer.dateline.date TEI.text.body.div.div.closer.dateline TEI.text.body.div.div.closer.signed.hi TEI.text.body.div.div.closer.signed.lb TEI.text.body.div.div.closer.signed.hi.persName.addName TEI.text.body.div.div.closer.signed.hi.persName TEI.text.body.div.div.closer.signed.hi TEI.text.body.div.div.closer.signed TEI.text.body.div.div.closer TEI.text.body.div.div TEI.text.body.div.div.div.pb TEI.text.body.div.div.div.fw TEI.text.body.div.div.div.head.app.lem.mod.del TEI.text.body.div.div.div.head.app.lem.mod TEI.text.body.div.div.div.head.app.lem TEI.text.body.div.div.div.head.app.rdg.mod TEI.text.body.div.div.div.head.app.rdg TEI.text.body.div.div.div.head.app TEI.text.body.div.div.div.head TEI.text.body.div.div.div.metamark TEI.text.body.div.div.div.head.app.lem.mod.subst.del TEI.text.body.div.div.div.head.app.lem.mod.subst.add TEI.text.body.div.div.div.head.app.lem.mod.subst TEI.text.body.div.div.div.head.app.lem.mod TEI.text.body.div.div.div.head.app.lem TEI.text.body.div.div.div.head.app.rdg.mod TEI.text.body.div.div.div.head.app.rdg TEI.text.body.div.div.div.head.app TEI.text.body.div.div.div.head TEI.text.body.div.div.div.metamark.mod.delSpan TEI.text.body.div.div.div.metamark.mod.lg.l TEI.text.body.div.div.div.metamark.mod.lg.l TEI.text.body.div.div.div.metamark.mod.lg.l TEI.text.body.div.div.div.metamark.mod.lg.l TEI.text.body.div.div.div.metamark.mod.lg.anchor TEI.text.body.div.div.div.metamark.mod.lg TEI.text.body.div.div.div.metamark.mod TEI.text.body.div.div.div.metamark TEI.text.body.div.div.div TEI.text.body.div.div.div.div.pb TEI.text.body.div.div.div.div.fw TEI.text.body.div.div.div.div TEI.text.body.div.div.div.div.pb TEI.text.body.div.div.div.div.fw TEI.text.body.div.div.div.div.fw TEI.text.body.div.div.div.div.metamark TEI.text.body.div.div.div.div.ab.mod.add.note TEI.text.body.div.div.div.div.ab.mod.add TEI.text.body.div.div.div.div.ab.mod TEI.text.body.div.div.div.div.ab TEI.text.body.div.div.div.div.div.head TEI.text.body.div.div.div.div.div.lb TEI.text.body.div.div.div.div.div.lg.l TEI.text.body.div.div.div.div.div.lg.l TEI.text.body.div.div.div.div.div.lg.l TEI.text.body.div.div.div.div.div.lg.l TEI.text.body.div.div.div.div.div.lg TEI.text.body.div.div.div.div.div.lg.l TEI.text.body.div.div.div.div.div.lg.l TEI.text.body.div.div.div.div.div.lg.l TEI.text.body.div.div.div.div.div.lg.l.app.lem.mod.del TEI.text.body.div.div.div.div.div.lg.l.app.lem.mod TEI.text.body.div.div.div.div.div.lg.l.app.lem TEI.text.body.div.div.div.div.div.lg.l.app.rdg.mod TEI.text.body.div.div.div.div.div.lg.l.app.rdg TEI.text.body.div.div.div.div.div.lg.l.app TEI.text.body.div.div.div.div.div.lg.l TEI.text.body.div.div.div.div.div.lg TEI.text.body.div.div.div.div.div.lg.l.app.lem.mod.subst.del TEI.text.body.div.div.div.div.div.lg.l.app.lem.mod.subst.add TEI.text.body.div.div.div.div.div.lg.l.app.lem.mod.subst TEI.text.body.div.div.div.div.div.lg.l.app.lem.mod TEI.text.body.div.div.div.div.div.lg.l.app.lem TEI.text.body.div.div.div.div.div.lg.l.app.rdg.mod TEI.text.body.div.div.div.div.div.lg.l.app.rdg TEI.text.body.div.div.div.div.div.lg.l.app TEI.text.body.div.div.div.div.div.lg.l TEI.text.body.div.div.div.div.div.lg.l TEI.text.body.div.div.div.div.div.lg.l.app.lem.mod.add TEI.text.body.div.div.div.div.div.lg.l.app.lem.mod.retrace TEI.text.body.div.div.div.div.div.lg.l.app.lem.mod TEI.text.body.div.div.div.div.div.lg.l.app.lem TEI.text.body.div.div.div.div.div.lg.l.app.rdg.mod TEI.text.body.div.div.div.div.div.lg.l.app.rdg TEI.text.body.div.div.div.div.div.lg.l.app TEI.text.body.div.div.div.div.div.lg.l TEI.text.body.div.div.div.div.div.lg.l.mod.subst.del TEI.text.body.div.div.div.div.div.lg.l.mod.subst.add TEI.text.body.div.div.div.div.div.lg.l.mod.subst TEI.text.body.div.div.div.div.div.lg.l.mod TEI.text.body.div.div.div.div.div.lg.l TEI.text.body.div.div.div.div.div.lg TEI.text.body.div.div.div.div.div.lg.l TEI.text.body.div.div.div.div.div.lg.l TEI.text.body.div.div.div.div.div.lg.l TEI.text.body.div.div.div.div.div.lg.l.choice.sic TEI.text.body.div.div.div.div.div.lg.l.choice.corr TEI.text.body.div.div.div.div.div.lg.l.choice TEI.text.body.div.div.div.div.div.lg.l TEI.text.body.div.div.div.div.div.lg TEI.text.body.div.div.div.div.div TEI.text.body.div.div.div.div TEI.text.body.div.div.div.div.pb TEI.text.body.div.div.div.div.fw TEI.text.body.div.div.div.div.fw TEI.text.body.div.div.div.div.metamark TEI.text.body.div.div.div.div.div.head TEI.text.body.div.div.div.div.div.lb TEI.text.body.div.div.div.div.div.lg.l TEI.text.body.div.div.div.div.div.lg.l TEI.text.body.div.div.div.div.div.lg.l TEI.text.body.div.div.div.div.div.lg.l TEI.text.body.div.div.div.div.div.lg TEI.text.body.div.div.div.div.div.lg.l TEI.text.body.div.div.div.div.div.lg.l TEI.text.body.div.div.div.div.div.lg.l.mod.add TEI.text.body.div.div.div.div.div.lg.l.mod TEI.text.body.div.div.div.div.div.lg.l TEI.text.body.div.div.div.div.div.lg.l TEI.text.body.div.div.div.div.div.lg TEI.text.body.div.div.div.div.div.lg.l TEI.text.body.div.div.div.div.div.lg.l TEI.text.body.div.div.div.div.div.lg.l TEI.text.body.div.div.div.div.div.lg TEI.text.body.div.div.div.div.div.lg.l.app.lem.mod.subst.del TEI.text.body.div.div.div.div.div.lg.l.app.lem.mod.subst.add TEI.text.body.div.div.div.div.div.lg.l.app.lem.mod.subst TEI.text.body.div.div.div.div.div.lg.l.app.lem.mod TEI.text.body.div.div.div.div.div.lg.l.app.lem TEI.text.body.div.div.div.div.div.lg.l.app.rdg.mod TEI.text.body.div.div.div.div.div.lg.l.app.rdg TEI.text.body.div.div.div.div.div.lg.l.app TEI.text.body.div.div.div.div.div.lg.l TEI.text.body.div.div.div.div.div.lg.l TEI.text.body.div.div.div.div.div.lg.l TEI.text.body.div.div.div.div.div.lg TEI.text.body.div.div.div.div.div.lb TEI.text.body.div.div.div.div.div.note.mod TEI.text.body.div.div.div.div.div.note TEI.text.body.div.div.div.div.div TEI.text.body.div.div.div.div.milestone TEI.text.body.div.div.div.div.note.mod.add TEI.text.body.div.div.div.div.note.mod TEI.text.body.div.div.div.div.note TEI.text.body.div.div.div.div.lb TEI.text.body.div.div.div.div.anchor TEI.text.body.div.div.div.div.div.head TEI.text.body.div.div.div.div.div.lb TEI.text.body.div.div.div.div.div.lg.l TEI.text.body.div.div.div.div.div.lg.l TEI.text.body.div.div.div.div.div.lg.l TEI.text.body.div.div.div.div.div.lg.l TEI.text.body.div.div.div.div.div.lg TEI.text.body.div.div.div.div.div.lg.l TEI.text.body.div.div.div.div.div.lg.l TEI.text.body.div.div.div.div.div.lg.l TEI.text.body.div.div.div.div.div.lg.l.mod.subst.add TEI.text.body.div.div.div.div.div.lg.l.mod.subst.del TEI.text.body.div.div.div.div.div.lg.l.mod.subst TEI.text.body.div.div.div.div.div.lg.l.mod TEI.text.body.div.div.div.div.div.lg.l TEI.text.body.div.div.div.div.div.lg TEI.text.body.div.div.div.div.div.lg.l.mod.subst.del TEI.text.body.div.div.div.div.div.lg.l.mod.subst.add TEI.text.body.div.div.div.div.div.lg.l.mod.subst TEI.text.body.div.div.div.div.div.lg.l.mod TEI.text.body.div.div.div.div.div.lg.l TEI.text.body.div.div.div.div.div.lg.l TEI.text.body.div.div.div.div.div.lg.l TEI.text.body.div.div.div.div.div.lg TEI.text.body.div.div.div.div.div.lg.l TEI.text.body.div.div.div.div.div.lg.l TEI.text.body.div.div.div.div.div.lg.l TEI.text.body.div.div.div.div.div.lg TEI.text.body.div.div.div.div.div TEI.text.body.div.div.div.div.pb TEI.text.body.div.div.div.div.div.head.app.lem TEI.text.body.div.div.div.div.div.head.app.rdg TEI.text.body.div.div.div.div.div.head.app TEI.text.body.div.div.div.div.div.head TEI.text.body.div.div.div.div.div.note.title TEI.text.body.div.div.div.div.div.note.title TEI.text.body.div.div.div.div.div.note TEI.text.body.div.div.div.div.div.lb TEI.text.body.div.div.div.div.div.lg.l TEI.text.body.div.div.div.div.div.lg.l.choice.corr.mod.del TEI.text.body.div.div.div.div.div.lg.l.choice.corr.mod TEI.text.body.div.div.div.div.div.lg.l.choice.corr TEI.text.body.div.div.div.div.div.lg.l.choice.sic TEI.text.body.div.div.div.div.div.lg.l.choice TEI.text.body.div.div.div.div.div.lg.l TEI.text.body.div.div.div.div.div.lg.l TEI.text.body.div.div.div.div.div.lg.l.subst.del.gap TEI.text.body.div.div.div.div.div.lg.l.subst.del TEI.text.body.div.div.div.div.div.lg.l.subst.add TEI.text.body.div.div.div.div.div.lg.l.subst TEI.text.body.div.div.div.div.div.lg.l.mod.add TEI.text.body.div.div.div.div.div.lg.l.mod TEI.text.body.div.div.div.div.div.lg.l TEI.text.body.div.div.div.div.div.lg TEI.text.body.div.div.div.div.div.lg.l TEI.text.body.div.div.div.div.div.lg.l.app.lem.mod.subst.del TEI.text.body.div.div.div.div.div.lg.l.app.lem.mod.subst.add TEI.text.body.div.div.div.div.div.lg.l.app.lem.mod.subst TEI.text.body.div.div.div.div.div.lg.l.app.lem.mod TEI.text.body.div.div.div.div.div.lg.l.app.lem TEI.text.body.div.div.div.div.div.lg.l.app.rdg.mod TEI.text.body.div.div.div.div.div.lg.l.app.rdg TEI.text.body.div.div.div.div.div.lg.l.app TEI.text.body.div.div.div.div.div.lg.l TEI.text.body.div.div.div.div.div.lg.l TEI.text.body.div.div.div.div.div.lg.l TEI.text.body.div.div.div.div.div.lg TEI.text.body.div.div.div.div.div.lg.l.mod.subst.del TEI.text.body.div.div.div.div.div.lg.l.mod.subst.add TEI.text.body.div.div.div.div.div.lg.l.mod.subst TEI.text.body.div.div.div.div.div.lg.l.mod TEI.text.body.div.div.div.div.div.lg.l.mod.add TEI.text.body.div.div.div.div.div.lg.l.mod TEI.text.body.div.div.div.div.div.lg.l TEI.text.body.div.div.div.div.div.lg.l TEI.text.body.div.div.div.div.div.lg.l TEI.text.body.div.div.div.div.div.lg.l TEI.text.body.div.div.div.div.div.lg TEI.text.body.div.div.div.div.div TEI.text.body.div.div.div.div TEI.text.body.div.div.div.div.pb TEI.text.body.div.div.div.div.fw TEI.text.body.div.div.div.div.fw TEI.text.body.div.div.div.div.metamark TEI.text.body.div.div.div.div.div.head TEI.text.body.div.div.div.div.div.lb TEI.text.body.div.div.div.div.div.lg.l TEI.text.body.div.div.div.div.div.lg.l TEI.text.body.div.div.div.div.div.lg.l TEI.text.body.div.div.div.div.div.lg.l TEI.text.body.div.div.div.div.div.lg TEI.text.body.div.div.div.div.div.lg.l TEI.text.body.div.div.div.div.div.lg.l TEI.text.body.div.div.div.div.div.lg.l TEI.text.body.div.div.div.div.div.lg.l TEI.text.body.div.div.div.div.div.lg TEI.text.body.div.div.div.div.div.lg.l TEI.text.body.div.div.div.div.div.lg.l TEI.text.body.div.div.div.div.div.lg.l TEI.text.body.div.div.div.div.div.lg TEI.text.body.div.div.div.div.div.lg.l TEI.text.body.div.div.div.div.div.lg.l TEI.text.body.div.div.div.div.div.lg.l TEI.text.body.div.div.div.div.div.lg TEI.text.body.div.div.div.div.div TEI.text.body.div.div.div.div.div.head TEI.text.body.div.div.div.div.div.lb TEI.text.body.div.div.div.div.div.lg.l TEI.text.body.div.div.div.div.div.lg.l TEI.text.body.div.div.div.div.div.lg.l TEI.text.body.div.div.div.div.div.lg.l TEI.text.body.div.div.div.div.div.lg TEI.text.body.div.div.div.div.div.lg.l TEI.text.body.div.div.div.div.div.lg.l TEI.text.body.div.div.div.div.div.lg.l TEI.text.body.div.div.div.div.div.lg.l TEI.text.body.div.div.div.div.div.lg TEI.text.body.div.div.div.div.div.lg.l TEI.text.body.div.div.div.div.div.lg.l.choice.sic TEI.text.body.div.div.div.div.div.lg.l.choice.corr TEI.text.body.div.div.div.div.div.lg.l.choice TEI.text.body.div.div.div.div.div.lg.l TEI.text.body.div.div.div.div.div.lg.l TEI.text.body.div.div.div.div.div.lg TEI.text.body.div.div.div.div.div.lg.l TEI.text.body.div.div.div.div.div.lg.l TEI.text.body.div.div.div.div.div.lg.l TEI.text.body.div.div.div.div.div.lg TEI.text.body.div.div.div.div.div TEI.text.body.div.div.div.div TEI.text.body.div.div.div.div.pb TEI.text.body.div.div.div.div.fw TEI.text.body.div.div.div.div.fw TEI.text.body.div.div.div.div.metamark TEI.text.body.div.div.div.div.head TEI.text.body.div.div.div.div.lb TEI.text.body.div.div.div.div.lg.l TEI.text.body.div.div.div.div.lg.l TEI.text.body.div.div.d

In [9]:
tfidf_docs.shape

(15, 2720)

In [11]:
from sklearn.cluster import HDBSCAN
labels = HDBSCAN( min_cluster_size=2, metric='cosine' ).fit_predict( tfidf_docs )

/Users/joris/Workspace/THINK/conflint/representation/.venv/lib/python3.12/site-packages/sklearn/cluster/_hdbscan/hdbscan.py:722: FutureWarning: The default value of `copy` will change from False to True in 1.10. Explicitly set a value for `copy` to silence this warning.
  warn(

In [12]:
labels

array([ 1, -1,  3,  3,  2,  1,  0,  0, -1, -1, -1, -1,  2,  2, -1])

In [15]:
import numpy as np

In [17]:
feature_names = np.array(doc_vectorizer.get_feature_names_out())

tfidf_docs_df = pandas.DataFrame( tfidf_docs.toarray() )
tfidf_docs_df['cluster'] = labels

cluster_editions = pandas.DataFrame( [ file_path.split('/')[-1].split('.')[-2] for file_path in file_paths ], index=labels )

print( feature_names )
print( 'Number of features:', len( feature_names ) )
display( cluster_editions )
tfidf_docs_df

['CURSUS' 'CURSUS.text' 'CURSUS.text.body' ...
 'div.text.body.div.ab.title.space' 'div.text.body.div.ab.unclear'
 'div.text.body.div.ab.unclear.pc']
Number of features: 2720

                                                   0
 1                                Digital-marco-polo
-1                 Chartes-de-labbaye-de-Saint-Denis
 3                                       Petrarchive
 3                                       leopardi(_)
 2                                    beckettarchive
 1                          Chronik-Ulrich-Richental
 0                                 Der arme Heinrich
 0                  Lyrik-des-deutschen-Mittelalters
-1  4earlyChanTextsFromDunhuang_aTEIbasedEdition2017
-1    CURSUS-OnlineResourceOfMedievalLiturgicalTexts
-1                                          Van-gogh
-1                                            CoReMa
 2                                             Faust
 2                                     Kaiserchronik
-1                                              saba

,0,1,2,3,4,5,6,7,8,9,...,2711,2712,2713,2714,2715,2716,2717,2718,2719,cluster
0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.00000,0.000000,0.00000,1
1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.00000,0.000000,0.00000,-1
2,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.00000,0.000000,0.00000,3
3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.00000,0.000000,0.00000,3
4,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.00000,0.000000,0.00000,2
5,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.00000,0.000000,0.00000,1
6,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.00000,0.000000,0.00000,0
7,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.00000,0.000000,0.00000,0
8,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.003907,0.003447,0.00023,0.002298,0.001839,0.000689,0.00023,0.007125,0.00046,-1
9,0.003853,0.003853,0.003853,0.030822,0.446925,0.446925,0.446925,0.446925,0.446925,0.007706,...,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.00000,0.000000,0.00000,-1
10,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.00000,0.000000,0.00000,-1
11,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.00000,0.000000,0.00000,-1
12,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.00000,0.000000,0.00000,2
13,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.00000,0.000000,0.00000,2
14,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.00000,0.000000,0.00000,-1

In [34]:
# Mean TF-IDF weight per term per cluster
cluster_means = tfidf_docs_df.groupby('cluster').mean()

# Top terms per cluster
report = ''
for idx, c in enumerate( cluster_means.index ):
    top = cluster_means.loc[c].sort_values(ascending=False).head(15)
    report += f'\n--- Cluster {idx} --- \n\nEditions:\n'
    for edition in cluster_editions.loc[c][0]:
        report += f'  * {edition}\n'
    report += '\nTerms frequently used in this cluster, rare in others:\n'
    for item in ( list( zip( feature_names[top.index.astype(int)], top[:15] ) ) ):
        report += f'  ({round( item[1], 4 ):.4f})  {item[0]}\n'
    report += f'{{sub_report_{idx}}}\n'

print( report )

--- Cluster 0 ---

Editions:
  * Chartes-de-labbaye-de-Saint-Denis
  * 4earlyChanTextsFromDunhuang_aTEIbasedEdition2017
  * CURSUS-OnlineResourceOfMedievalLiturgicalTexts
  * Van-gogh
  * CoReMa
  * saba

Terms frequently used in this cluster, rare in others:
  (0.1442)  TEI.text.body.ab.seg.g
  (0.1369)  TEI.text.body.div.ab.lb
  (0.1244)  TEI.text.body.div.div.div.div.lg.l
  (0.1171)  div.text.body.div.ab.orig
  (0.0882)  div.text.body.div.ab.pc
  (0.0835)  TEI.text.group.text.body.div.listWit.listWit.witness
  (0.0820)  TEI.text.body.div.div.div.div.div.lg.l
  (0.0767)  div.text.body.div.ab.orig.g
  (0.0745)  CURSUS.text.body.chapter.verse.reference
  (0.0745)  CURSUS.text.body.chapter.verse.reference.bookName
  (0.0745)  CURSUS.text.body.chapter.verse.l
  (0.0745)  CURSUS.text.body.chapter.verse
  (0.0745)  CURSUS.text.body.chapter.verse.reference.verseNum
  (0.0502)  TEI.text.body.div.ab.c
  (0.0480)  TEI.text.body.div.ab
{sub_report_0}

--- Cluster 1 ---

Editions:
  * Der arme Heinrich
  * Lyrik-des-deutschen-Mittelalters

Terms frequently used in this cluster, rare in others:
  (0.3335)  TEI.text.body.div.lg.l.w
  (0.3025)  TEI.text.body.div.lg.l.app.rdg
  (0.2125)  TEI.text.body.div.lg.l.app.rdg.choice
  (0.2072)  TEI.text.body.div.lg.l.w.choice
  (0.2012)  TEI.text.body.div.lg.l.app.rdg.choice.reg
  (0.2011)  TEI.text.body.div.lg.l.app.rdg.choice.orig
  (0.1980)  TEI.text.body.div.lg.l.w.choice.reg
  (0.1828)  TEI.text.body.div.lg.l.w.choice.orig
  (0.1644)  TEI.text.body.div.lg.l.app.rdg.pc
  (0.0899)  TEI.text.body.div.lg.l
  (0.0641)  TEI.text.body.div.lg.l.pc.choice.reg
  (0.0641)  TEI.text.body.div.lg.l.pc.choice.orig
  (0.0641)  TEI.text.body.div.lg.l.pc.choice
  (0.0641)  TEI.text.body.div.lg.l.pc
  (0.0426)  TEI.text.body.div.lg.l.app
{sub_report_1}

--- Cluster 2 ---

Editions:
  * Digital-marco-polo
  * Chronik-Ulrich-Richental

Terms frequently used in this cluster, rare in others:
  (0.4755)  TEI.text.body.div.p.lb
  (0.4566)  TEI.text.body.div.p.note.hi
  (0.1897)  TEI.text.body.div.p.hi
  (0.1360)  TEI.text.body.div.p.pc
  (0.0636)  TEI.text.body.div.p.note
  (0.0448)  TEI.text.body.div.p.placeName
  (0.0278)  TEI.text.body.div.p.term
  (0.0242)  TEI.text.body.div.p.persName
  (0.0241)  TEI.text.body.div.head.lb
  (0.0238)  TEI.text.body.div.p
  (0.0226)  TEI.text.body.div.linkGrp.link
  (0.0226)  TEI.text.body.div.linkGrp
  (0.0199)  TEI.text.body.div.p.pb
  (0.0148)  TEI.text.body.div
  (0.0146)  TEI.text.body.div.listPlace.place.placeName
{sub_report_2}

--- Cluster 3 ---

Editions:
  * beckettarchive
  * Faust
  * Kaiserchronik

Terms frequently used in this cluster, rare in others:
  (0.3193)  TEI.sourceDoc.surface.zone.line
  (0.2646)  TEI.teiHeader.profileDesc.handNotes.handNote
  (0.2312)  TEI.text.body.div.sp.p.seg
  (0.1636)  TEI.text.body.div.sp.p.seg.lb
  (0.1599)  TEI.text.group.text.body.div.sp.l
  (0.1001)  TEI.text.group.text.body.div.sp.lg.l
  (0.0941)  TEI.sourceDoc.surface.zone.line.choice
  (0.0941)  TEI.sourceDoc.surface.zone.line.choice.expan
  (0.0941)  TEI.sourceDoc.surface.zone.line.choice.abbr
  (0.0703)  TEI.text.body.div.sp.p.seg.stage.hi
  (0.0703)  TEI.text.body.div.sp.p.seg.stage
  (0.0460)  TEI.text.body.div.sp.p.seg.add
  (0.0448)  TEI.text.body.div.div.sp.p.seg.lb
  (0.0446)  TEI.text.body.div.sp.p.seg.del
  (0.0410)  TEI.text.group.text.body.sp.l
{sub_report_3}

--- Cluster 4 ---

Editions:
  * Petrarchive
  * leopardi(_)

Terms frequently used in this cluster, rare in others:
  (0.2915)  TEI.text.body.lg.lg.lg.l.choice
  (0.2751)  TEI.text.body.lg.l.app.rdg
  (0.2552)  TEI.text.body.lg.lg.lg.l.choice.orig
  (0.2549)  TEI.text.body.lg.lg.lg.l.choice.reg
  (0.2459)  TEI.text.body.lg.l.app.rdg.mod
  (0.2016)  TEI.text.body.lg.l.app
  (0.2016)  TEI.text.body.lg.l.app.lem
  (0.1707)  TEI.text.body.lg.l
  (0.1172)  TEI.text.body.lg.lg.lg.l
  (0.0667)  TEI.teiHeader.encodingDesc.tagsDecl.rendition
  (0.0604)  TEI.text.body.lg.lg.lg
  (0.0371)  TEI.teiHeader.fileDesc.sourceDesc.bibl.editor
  (0.0364)  TEI.text.body.lg.lg.lg.l.choice.expan
  (0.0364)  TEI.text.body.lg.lg.lg.l.choice.abbr
  (0.0355)  TEI.text.body.lg.lg.lg.l.supplied
{sub_report_4}

The above tells us what features are most used in the documents pertaining to a cluster.

We can use some different logic to see what features actually discriminate between clusters.

In [35]:
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression(max_iter=1000, C=1.0 )
clf.fit(tfidf_docs, labels)

sub_reports = []

for i, c in enumerate(clf.classes_):
    coefs = clf.coef_[i]
    top = np.argsort(coefs)[-15:][::-1]
    sub_report = f"\nCluster {i} Top distinguishing terms:\n"
    for item in list( zip( feature_names[top], coefs[top].round(3) ) ):
        sub_report += f'  ({round( item[1], 4 ):.4f})  {item[0]}\n'
    sub_reports.append( sub_report )

report = report.format_map( {f'sub_report_{i}': s for i, s in enumerate( sub_reports ) } )

print( report )

with open( './distinguishing_tei_editions_simpler.md', 'w' ) as report_file:
    report_file.write( report )

--- Cluster 0 ---

Editions:
  * Chartes-de-labbaye-de-Saint-Denis
  * 4earlyChanTextsFromDunhuang_aTEIbasedEdition2017
  * CURSUS-OnlineResourceOfMedievalLiturgicalTexts
  * Van-gogh
  * CoReMa
  * saba

Terms frequently used in this cluster, rare in others:
  (0.1442)  TEI.text.body.ab.seg.g
  (0.1369)  TEI.text.body.div.ab.lb
  (0.1244)  TEI.text.body.div.div.div.div.lg.l
  (0.1171)  div.text.body.div.ab.orig
  (0.0882)  div.text.body.div.ab.pc
  (0.0835)  TEI.text.group.text.body.div.listWit.listWit.witness
  (0.0820)  TEI.text.body.div.div.div.div.div.lg.l
  (0.0767)  div.text.body.div.ab.orig.g
  (0.0745)  CURSUS.text.body.chapter.verse.reference
  (0.0745)  CURSUS.text.body.chapter.verse.reference.bookName
  (0.0745)  CURSUS.text.body.chapter.verse.l
  (0.0745)  CURSUS.text.body.chapter.verse
  (0.0745)  CURSUS.text.body.chapter.verse.reference.verseNum
  (0.0502)  TEI.text.body.div.ab.c
  (0.0480)  TEI.text.body.div.ab

Cluster 0 Top distinguishing terms:
  (0.3910)  TEI.text.body.ab.seg.g
  (0.3720)  TEI.text.body.div.ab.lb
  (0.3380)  TEI.text.body.div.div.div.div.lg.l
  (0.3180)  div.text.body.div.ab.orig
  (0.2390)  div.text.body.div.ab.pc
  (0.2270)  TEI.text.group.text.body.div.listWit.listWit.witness
  (0.2230)  TEI.text.body.div.div.div.div.div.lg.l
  (0.2080)  div.text.body.div.ab.orig.g
  (0.2020)  CURSUS.text.body.chapter.verse.reference.verseNum
  (0.2020)  CURSUS.text.body.chapter.verse.reference.bookName
  (0.2020)  CURSUS.text.body.chapter.verse.reference
  (0.2020)  CURSUS.text.body.chapter.verse.l
  (0.2020)  CURSUS.text.body.chapter.verse
  (0.1360)  TEI.text.body.div.ab.c
  (0.1300)  TEI.text.body.div.ab


--- Cluster 1 ---

Editions:
  * Der arme Heinrich
  * Lyrik-des-deutschen-Mittelalters

Terms frequently used in this cluster, rare in others:
  (0.3335)  TEI.text.body.div.lg.l.w
  (0.3025)  TEI.text.body.div.lg.l.app.rdg
  (0.2125)  TEI.text.body.div.lg.l.app.rdg.choice
  (0.2072)  TEI.text.body.div.lg.l.w.choice
  (0.2012)  TEI.text.body.div.lg.l.app.rdg.choice.reg
  (0.2011)  TEI.text.body.div.lg.l.app.rdg.choice.orig
  (0.1980)  TEI.text.body.div.lg.l.w.choice.reg
  (0.1828)  TEI.text.body.div.lg.l.w.choice.orig
  (0.1644)  TEI.text.body.div.lg.l.app.rdg.pc
  (0.0899)  TEI.text.body.div.lg.l
  (0.0641)  TEI.text.body.div.lg.l.pc.choice.reg
  (0.0641)  TEI.text.body.div.lg.l.pc.choice.orig
  (0.0641)  TEI.text.body.div.lg.l.pc.choice
  (0.0641)  TEI.text.body.div.lg.l.pc
  (0.0426)  TEI.text.body.div.lg.l.app

Cluster 1 Top distinguishing terms:
  (0.4790)  TEI.text.body.div.lg.l.w
  (0.4350)  TEI.text.body.div.lg.l.app.rdg
  (0.3050)  TEI.text.body.div.lg.l.app.rdg.choice
  (0.2980)  TEI.text.body.div.lg.l.w.choice
  (0.2890)  TEI.text.body.div.lg.l.app.rdg.choice.reg
  (0.2890)  TEI.text.body.div.lg.l.app.rdg.choice.orig
  (0.2850)  TEI.text.body.div.lg.l.w.choice.reg
  (0.2630)  TEI.text.body.div.lg.l.w.choice.orig
  (0.2360)  TEI.text.body.div.lg.l.app.rdg.pc
  (0.1290)  TEI.text.body.div.lg.l
  (0.0920)  TEI.text.body.div.lg.l.pc
  (0.0920)  TEI.text.body.div.lg.l.pc.choice.reg
  (0.0920)  TEI.text.body.div.lg.l.pc.choice.orig
  (0.0920)  TEI.text.body.div.lg.l.pc.choice
  (0.0610)  TEI.text.body.div.lg.l.app


--- Cluster 2 ---

Editions:
  * Digital-marco-polo
  * Chronik-Ulrich-Richental

Terms frequently used in this cluster, rare in others:
  (0.4755)  TEI.text.body.div.p.lb
  (0.4566)  TEI.text.body.div.p.note.hi
  (0.1897)  TEI.text.body.div.p.hi
  (0.1360)  TEI.text.body.div.p.pc
  (0.0636)  TEI.text.body.div.p.note
  (0.0448)  TEI.text.body.div.p.placeName
  (0.0278)  TEI.text.body.div.p.term
  (0.0242)  TEI.text.body.div.p.persName
  (0.0241)  TEI.text.body.div.head.lb
  (0.0238)  TEI.text.body.div.p
  (0.0226)  TEI.text.body.div.linkGrp.link
  (0.0226)  TEI.text.body.div.linkGrp
  (0.0199)  TEI.text.body.div.p.pb
  (0.0148)  TEI.text.body.div
  (0.0146)  TEI.text.body.div.listPlace.place.placeName

Cluster 2 Top distinguishing terms:
  (0.6840)  TEI.text.body.div.p.lb
  (0.6570)  TEI.text.body.div.p.note.hi
  (0.2730)  TEI.text.body.div.p.hi
  (0.1960)  TEI.text.body.div.p.pc
  (0.0920)  TEI.text.body.div.p.note
  (0.0640)  TEI.text.body.div.p.placeName
  (0.0400)  TEI.text.body.div.p.term
  (0.0350)  TEI.text.body.div.p.persName
  (0.0350)  TEI.text.body.div.head.lb
  (0.0330)  TEI.text.body.div.p
  (0.0320)  TEI.text.body.div.linkGrp
  (0.0320)  TEI.text.body.div.linkGrp.link
  (0.0290)  TEI.text.body.div.p.pb
  (0.0210)  TEI.text.body.div.listPlace.place.placeName
  (0.0210)  TEI.text.body.div.listPlace.place


--- Cluster 3 ---

Editions:
  * beckettarchive
  * Faust
  * Kaiserchronik

Terms frequently used in this cluster, rare in others:
  (0.3193)  TEI.sourceDoc.surface.zone.line
  (0.2646)  TEI.teiHeader.profileDesc.handNotes.handNote
  (0.2312)  TEI.text.body.div.sp.p.seg
  (0.1636)  TEI.text.body.div.sp.p.seg.lb
  (0.1599)  TEI.text.group.text.body.div.sp.l
  (0.1001)  TEI.text.group.text.body.div.sp.lg.l
  (0.0941)  TEI.sourceDoc.surface.zone.line.choice
  (0.0941)  TEI.sourceDoc.surface.zone.line.choice.expan
  (0.0941)  TEI.sourceDoc.surface.zone.line.choice.abbr
  (0.0703)  TEI.text.body.div.sp.p.seg.stage.hi
  (0.0703)  TEI.text.body.div.sp.p.seg.stage
  (0.0460)  TEI.text.body.div.sp.p.seg.add
  (0.0448)  TEI.text.body.div.div.sp.p.seg.lb
  (0.0446)  TEI.text.body.div.sp.p.seg.del
  (0.0410)  TEI.text.group.text.body.sp.l

Cluster 3 Top distinguishing terms:
  (0.6010)  TEI.sourceDoc.surface.zone.line
  (0.4980)  TEI.teiHeader.profileDesc.handNotes.handNote
  (0.4430)  TEI.text.body.div.sp.p.seg
  (0.3130)  TEI.text.body.div.sp.p.seg.lb
  (0.3010)  TEI.text.group.text.body.div.sp.l
  (0.1880)  TEI.text.group.text.body.div.sp.lg.l
  (0.1770)  TEI.sourceDoc.surface.zone.line.choice.abbr
  (0.1770)  TEI.sourceDoc.surface.zone.line.choice.expan
  (0.1770)  TEI.sourceDoc.surface.zone.line.choice
  (0.1350)  TEI.text.body.div.sp.p.seg.stage.hi
  (0.1350)  TEI.text.body.div.sp.p.seg.stage
  (0.0880)  TEI.text.body.div.sp.p.seg.add
  (0.0860)  TEI.text.body.div.div.sp.p.seg.lb
  (0.0850)  TEI.text.body.div.sp.p.seg.del
  (0.0770)  TEI.text.group.text.body.sp.l


--- Cluster 4 ---

Editions:
  * Petrarchive
  * leopardi(_)

Terms frequently used in this cluster, rare in others:
  (0.2915)  TEI.text.body.lg.lg.lg.l.choice
  (0.2751)  TEI.text.body.lg.l.app.rdg
  (0.2552)  TEI.text.body.lg.lg.lg.l.choice.orig
  (0.2549)  TEI.text.body.lg.lg.lg.l.choice.reg
  (0.2459)  TEI.text.body.lg.l.app.rdg.mod
  (0.2016)  TEI.text.body.lg.l.app
  (0.2016)  TEI.text.body.lg.l.app.lem
  (0.1707)  TEI.text.body.lg.l
  (0.1172)  TEI.text.body.lg.lg.lg.l
  (0.0667)  TEI.teiHeader.encodingDesc.tagsDecl.rendition
  (0.0604)  TEI.text.body.lg.lg.lg
  (0.0371)  TEI.teiHeader.fileDesc.sourceDesc.bibl.editor
  (0.0364)  TEI.text.body.lg.lg.lg.l.choice.expan
  (0.0364)  TEI.text.body.lg.lg.lg.l.choice.abbr
  (0.0355)  TEI.text.body.lg.lg.lg.l.supplied

Cluster 4 Top distinguishing terms:
  (0.4190)  TEI.text.body.lg.lg.lg.l.choice
  (0.3960)  TEI.text.body.lg.l.app.rdg
  (0.3670)  TEI.text.body.lg.lg.lg.l.choice.orig
  (0.3670)  TEI.text.body.lg.lg.lg.l.choice.reg
  (0.3540)  TEI.text.body.lg.l.app.rdg.mod
  (0.2900)  TEI.text.body.lg.l.app.lem
  (0.2900)  TEI.text.body.lg.l.app
  (0.2460)  TEI.text.body.lg.l
  (0.1690)  TEI.text.body.lg.lg.lg.l
  (0.0950)  TEI.teiHeader.encodingDesc.tagsDecl.rendition
  (0.0870)  TEI.text.body.lg.lg.lg
  (0.0530)  TEI.teiHeader.fileDesc.sourceDesc.bibl.editor
  (0.0520)  TEI.text.body.lg.lg.lg.l.choice.abbr
  (0.0520)  TEI.text.body.lg.lg.lg.l.choice.expan
  (0.0510)  TEI.text.body.lg.lg.lg.l.supplied